version: '3'
services:
  web:
    # MEMO: 
    # 公式で配布されているnginxを指定する。
    # Docker Hub でレポジトリとして保管されている。 
    image: nginx:1.24.0
    # MEMO:
    # Portsには、ホスト側:コンテナ側という表現でポート開放を示す。
    ports:
      - "8000:80"
    # MEMO:
    # Dockerコンテナにマウントしたいファイル群を指定する。
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html